{{- if .Values.mongo.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: {{ .Values.global.namespace }}
  labels:
    app: mongo
    app.kubernetes.io/name: {{ include "craftista.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: {{ .Values.mongo.database | quote }}
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
        resources:
          {{- toYaml .Values.mongo.resources | nindent 10 }}
      volumes:
      - name: mongo-storage
        {{- if .Values.mongo.persistence.enabled }}
        persistentVolumeClaim:
          claimName: mongo-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
{{- end }}