services:
  # Base de datos para el catálogo
  mongodb:
    image: mongo:5.0
    environment:
      MONGO_INITDB_DATABASE: catalogue
    volumes:
      - mongo_data:/data/db
    networks:
      - craftista-network
    
  # Base de datos para votaciones
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - craftista-network

  # Servicio del catálogo (Python/Flask)
  catalogue:
    build: ./catalogue
    environment:
      MONGO_URL: mongodb://mongodb:27017/catalogue
    depends_on:
      - mongodb
    networks:
      - craftista-network
    ports:
      - "5001:5000"

  # Servicio de votaciones (Java/Spring Boot)
  voting:
    build: ./voting
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
      - catalogue
    networks:
      - craftista-network
    ports:
      - "8080:8080"

  # Servicio de recomendaciones (Go)
  recommendation:
    build: ./recommendation
    environment:
      CATALOGUE_URL: http://catalogue:5000
      VOTING_URL: http://voting:8080
    depends_on:
      - catalogue
      - voting
    networks:
      - craftista-network
    ports:
      - "8082:8080"

  # Frontend (Node.js/Express)
  frontend:
    build: ./frontend
    environment:
      CATALOGUE_URL: http://catalogue:5000
      VOTING_URL: http://voting:8080
      RECOMMENDATION_URL: http://recommendation:8080
    depends_on:
      - voting
      - recommendation
    networks:
      - craftista-network
    ports:
      - "3000:3000"

networks:
  craftista-network:
    driver: bridge

volumes:
  mongo_data:
  postgres_data:

# Servicio         Puerto Externo   Puerto Interno   URL Externa
# frontend         3000             3000             http://localhost:3000
# catalogue        5001             5000             http://localhost:5001
# voting           8080             8080             http://localhost:8080
# recommendation   8082             8080             http://localhost:8082