# Global configuration
global:
  namespace: craftista
  imagePullPolicy: Always  # Cambiar de Never a Always
  registry: 651706751731.dkr.ecr.us-east-1.amazonaws.com

# Application services
frontend:
  enabled: true
  replicas: 2
  rollout:
    enabled: true
  image:
    repository: 651706751731.dkr.ecr.us-east-1.amazonaws.com/craftista/frontend
    tag: v1.0.0  # Tag inicial
  service:
    type: LoadBalancer
    port: 3000
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "300m"

catalogue:
  enabled: true
  replicas: 2
  image:
    repository: 651706751731.dkr.ecr.us-east-1.amazonaws.com/craftista/catalogue
    tag: v1.0.0
  service:
    type: ClusterIP
    port: 5000
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

voting:
  enabled: true
  replicas: 2
  image:
    repository: 651706751731.dkr.ecr.us-east-1.amazonaws.com/craftista/voting
    tag: v1.0.0
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      memory: "768Mi"
      cpu: "400m"
    limits:
      memory: "1.5Gi"
      cpu: "800m"

recommendation:
  enabled: true
  replicas: 2
  image:
    repository: 651706751731.dkr.ecr.us-east-1.amazonaws.com/craftista/recommendation
    tag: v1.0.0
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"