# k8s/voting/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: voting
  namespace: craftista
spec:
  selector:
    app: voting
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP