# k8s/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: craftista
type: Opaque
data:
  # Base64 encoded values
  POSTGRES_USER: Y3JhZnRpc3Rh        # craftista
  POSTGRES_PASSWORD: cGFzc3dvcmQ=     # password
  POSTGRES_DB: Y3JhZnRpc3Rh          # craftista

---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: craftista
type: Opaque
data:
  MONGO_INITDB_DATABASE: Y3JhZnRpc3Rh  # craftista

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: craftista
type: Opaque
data:
  # Database connection strings
  DATABASE_URL: cG9zdGdyZXNxbDovL2NyYWZ0aXN0YTpwYXNzd29yZEBwb3N0Z3Jlczo1NDMyL2NyYWZ0aXN0YQ==
  MONGO_URL: bW9uZ29kYjovL21vbmdvOjI3MDE3L2NyYWZ0aXN0YQ==