FROM golang:1.20 AS builder
WORKDIR /app
COPY . .
RUN go build -o app

FROM debian:stable-slim
WORKDIR /app
COPY --from=builder /app/app .
COPY --from=builder /app/templates ./templates/
ENV PORT=8080
EXPOSE ${PORT}
CMD ["./app"]
