# k8s/recomendation/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: recommendation
  namespace: craftista
spec:
  selector:
    app: recommendation
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP