apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "craftista.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.credentials.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password | b64enc }}
  POSTGRES_DB: {{ .Values.postgres.credentials.database | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "craftista.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  MONGO_INITDB_DATABASE: {{ .Values.mongo.database | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "craftista.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  DATABASE_URL: {{ printf "postgresql://%s:%s@postgres:5432/%s" .Values.postgres.credentials.username .Values.postgres.credentials.password .Values.postgres.credentials.database | b64enc }}
  MONGO_URL: {{ printf "mongodb://mongo:27017/%s" .Values.mongo.database | b64enc }}