{{- if and .Values.frontend.enabled .Values.frontend.rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    app: frontend
    app.kubernetes.io/name: {{ include "craftista.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 30s}
      - setWeight: 60
      - pause: {duration: 30s}
      - setWeight: 80
      - pause: {duration: 30s}
      canaryService: frontend-canary
      stableService: frontend-stable
      trafficRouting:
        nginx:
          stableIngress: frontend-ingress
          annotationPrefix: nginx.ingress.kubernetes.io
          additionalIngressAnnotations:
            canary-by-header: X-Canary
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.frontend.service.port }}
        env:
        - name: CATALOGUE_URL
          value: "http://catalogue:{{ .Values.catalogue.service.port }}"
        - name: RECOMMENDATION_URL
          value: "http://recommendation:{{ .Values.recommendation.service.port }}"
        - name: VOTING_URL
          value: "http://voting:{{ .Values.voting.service.port }}"
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.frontend.service.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.frontend.service.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 30s}
      - setWeight: 60
      - pause: {duration: 30s}
      - setWeight: 80
      - pause: {duration: 30s}
      canaryService: frontend-canary
      stableService: frontend-stable
      analysis:
        templates:
        - templateName: frontend-success-rate
        startingStep: 2
        args:
        - name: service-name
          value: frontend-canary
{{- end }}