{{- if .Values.frontend.rollout.enabled }}
{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    app: frontend
    app.kubernetes.io/name: {{ include "craftista.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.port }}
  type: {{ .Values.frontend.service.type }}
apiVersion: v1
kind: Service
metadata:
  name: frontend-stable
  namespace: {{ .Values.global.namespace }}
  labels:
    app: frontend
    service: stable
spec:
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.port }}
    protocol: TCP
  selector:
    app: frontend
  type: {{ .Values.frontend.service.type }}

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-canary
  namespace: {{ .Values.global.namespace }}
  labels:
    app: frontend
    service: canary
spec:
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.port }}
    protocol: TCP
  selector:
    app: frontend
  type: {{ .Values.frontend.service.type }}
{{- else }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    app: frontend
spec:
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.port }}
    protocol: TCP
  selector:
    app: frontend
  type: {{ .Values.frontend.service.type }}
{{- end }}
{{- end }}