name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install & Test Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm test

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install & Test Catalogue (Flask)
        working-directory: ./catalogue
        run: |
          pip install -r requirements.txt
          python3 -m unittest test_app.py

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build & Test Voting (Spring Boot)
        working-directory: ./voting
        run: |
          mvn -Dtest=com.example.voting.VotingApplicationTests test

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Test Recommendation (Go)
        working-directory: ./recommendation
        run: go test ./...
